services:
  # Banco de Dados PostGIS
  db:
    image: postgis/postgis:15-3.3
    container_name: toaki_geo_db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Redis (Para o Channels)
  redis:
    image: redis:7-alpine
    container_name: toaki_redis
    ports:
      - "6379:6379"

  # App Django
  web:
    build: .
    container_name: toaki_back
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - REDIS_URL=${REDIS_URL}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}

  frontend:
    build: ./frontend
    container_name: toaki_front
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY}
    depends_on:
      - web

volumes:
  postgres_data:
